private-miui-apps := AntiSpam  \
					 Backup  \
					 Browser  \
					 BugReport  \
					 Calculator  \
					 Calendar  \
					 CalendarProvider  \
					 ChromeBookmarksSyncAdapter  \
					 CloudService  \
					 Contacts  \
					 ContactsProvider  \
					 DeskClock  \
					 DownloadProvider  \
					 DownloadProviderUi  \
					 Email  \
					 FileExplorer  \
					 MiuiGallery  \
					 GoogleBackupTransport  \
					 GoogleCalendarSyncAdapter  \
					 GoogleContactsSyncAdapter  \
					 GoogleLoginService  \
					 GooglePartnerSetup  \
					 GoogleServicesFramework  \
					 LBESEC_MIUI  \
					 MediaProvider  \
					 MiuiCompass  \
					 MiuiHome  \
					 MiuiSystemUI  \
					 Mms  \
					 Music  \
					 NetworkLocation  \
					 Notes  \
					 PackageInstaller  \
					 Phone  \
					 Provision \
					 QuickSearchBox  \
					 Settings  \
					 SettingsProvider  \
					 SoundRecorder  \
					 SuperMarket  \
					 Stk  \
					 TelephonyProvider  \
					 TelocationProvider  \
					 ThemeManager  \
					 Updater \
					 Bluetooth \
					 Weather \
					 WeatherProvider \
					 GuardProvider \
					 NetworkAssistant \
					 XiaomiServiceFramework \
					 MiuiVideoPlayer \
					 VpnDialogs \
					 Exchange2 \
					 AirkanPhoneService

private-preinstall-apps := VoiceAssist  \
					 GameCenter \
					 GameCenterSDKService \
					 InputMethod \
					 AlipayMsp \
					 MiuiVideo \
					 MiShop \
					 Userbook
