private-miui-apps := AntiSpam  \
					 Backup  \
					 Browser  \
					 BugReport  \
					 Calculator  \
					 Calendar  \
					 CalendarProvider  \
					 ChromeBookmarksSyncAdapter  \
					 CloudService  \
					 Contacts  \
					 ContactsProvider  \
					 DeskClock  \
					 DownloadProvider  \
					 DownloadProviderUi  \
					 Email  \
					 Exchange \
					 FileExplorer  \
					 Gallery  \
					 Gmail  \
					 GoogleBackupTransport  \
					 GoogleCalendarSyncAdapter  \
					 GoogleContactsSyncAdapter  \
					 GoogleLoginService  \
					 GooglePartnerSetup  \
					 GoogleServicesFramework  \
					 LBESEC_MIUI  \
					 Maps  \
					 MediaProvider  \
					 MiuiCompass  \
					 MiuiHome  \
					 MiuiSystemUI  \
					 Mms  \
					 Monitor  \
					 Music  \
					 NetworkLocation  \
					 Notes  \
					 PackageInstaller  \
					 Phone  \
					 Provision \
					 QuickSearchBox  \
					 Settings  \
					 SoundRecorder  \
					 SuperMarket  \
					 Talk  \
					 TelephonyProvider  \
					 TelocationProvider  \
					 ThemeManager  \
					 Updater  \
					 Vending  \
					 VoiceSearch

